#!/usr/bin/env bash

DIR=/opt/dgamelaunch/cdda/dgldir/cdda_data/cdda_memorial
CEMETERY=/home/game_server/morgue/cemetery/
NEWFILE=""

inotifywait -m "$DIR" --format '%w%f' -e close_write |
    while read file; do
	echo $file "closed for reading"
	sleep 1
	cp $file $CEMETERY
	NEWFILE=`echo "${file#*/*/*/*/*/*/*/*}"`
	#echo $CEMETERY$NEWFILE
	NEWFILE=`echo $CEMETERY$NEWFILE`
	#test if file is swap, if not pass to autopsy
	echo $NEWFILE "- new destination"
	
	#test mode which only echos to stdout
	#./autopsy2 $NEWFILE
	./autopsy $file
    done
